#ifndef ABOMINATION_H
#define ABOMINATION_H


// Special Keys (Non-Printable)
#define KEYBOARD_KEYPAD_ENTER_PRESSED    0xE01C
#define KEYBOARD_RIGHT_CTRL_PRESSED      0xE01D
#define KEYBOARD_KEYPAD_SLASH_PRESSED    0xE035
#define KEYBOARD_RIGHT_ALT_PRESSED       0xE038
#define KEYBOARD_HOME_PRESSED            0xE047
#define KEYBOARD_CURSOR_UP_PRESSED       0xE048
#define KEYBOARD_PAGE_UP_PRESSED         0xE049
#define KEYBOARD_CURSOR_LEFT_PRESSED     0xE04B
#define KEYBOARD_CURSOR_RIGHT_PRESSED    0xE04D
#define KEYBOARD_END_PRESSED             0xE04F
#define KEYBOARD_CURSOR_DOWN_PRESSED     0xE050
#define KEYBOARD_PAGE_DOWN_PRESSED       0xE051
#define KEYBOARD_INSERT_PRESSED          0xE052
#define KEYBOARD_DELETE_PRESSED          0xE053
#define KEYBOARD_LEFT_GUI_PRESSED        0xE05B
#define KEYBOARD_RIGHT_GUI_PRESSED       0xE05C
#define KEYBOARD_APPS_PRESSED            0xE05D
#define KEYBOARD_WAKE_PRESSED            0xE063


// Released Keys (Non-Printable)
#define KEYBOARD_PREVIOUS_TRACK_RELEASED 0xE090
#define KEYBOARD_NEXT_TRACK_RELEASED     0xE099
#define KEYBOARD_KEYPAD_ENTER_RELEASED   0xE09C
#define KEYBOARD_RIGHT_CTRL_RELEASED     0xE09D
#define KEYBOARD_KEYPAD_SLASH_RELEASED   0xE0B5
#define KEYBOARD_RIGHT_ALT_RELEASED      0xE0B8
#define KEYBOARD_HOME_RELEASED           0xE0C7
#define KEYBOARD_CURSOR_UP_RELEASED      0xE0C8
#define KEYBOARD_PAGE_UP_RELEASED        0xE0C9
#define KEYBOARD_CURSOR_LEFT_RELEASED    0xE0CB
#define KEYBOARD_CURSOR_RIGHT_RELEASED   0xE0CD
#define KEYBOARD_END_RELEASED            0xE0CF
#define KEYBOARD_CURSOR_DOWN_RELEASED    0xE0D0
#define KEYBOARD_PAGE_DOWN_RELEASED      0xE0D1
#define KEYBOARD_INSERT_RELEASED         0xE0D2
#define KEYBOARD_DELETE_RELEASED         0xE0D3
#define KEYBOARD_LEFT_GUI_RELEASED       0xE0DB
#define KEYBOARD_RIGHT_GUI_RELEASED      0xE0DC
#define KEYBOARD_APPS_RELEASED           0xE0DD
#define KEYBOARD_WAKE_RELEASED           0xE0E3

// Pause (multi-byte)
#define KEYBOARD_PAUSE_PRESSED           0xE1


/*
// Enum for Easy Access to Non-Printable Keys
typedef enum {
    KEYBOARD_ESCAPE = 0x1B,
    KEYBOARD_F1 = 0x81,
    KEYBOARD_LEFT_CTRL = 0x1D,
    KEYBOARD_BACKSLASH = 0x5C,
    KEYBOARD_RIGHT_SHIFT = 0x36,
    KEYBOARD_NUMPAD_STAR = 0x37,
    KEYBOARD_CAPSLOCK = 0x3A,
    KEYBOARD_F2 = 0x82,
    KEYBOARD_LEFT_ALT = 0x38,
    KEYBOARD_SCROLLLOCK = 0x46,
    KEYBOARD_NUMLOCK = 0x45,
    KEYBOARD_F3 = 0x83,
    KEYBOARD_F4 = 0x84,
    KEYBOARD_F5 = 0x85,
    KEYBOARD_F6 = 0x86,
    KEYBOARD_F7 = 0x87,
    KEYBOARD_F8 = 0x88,
    KEYBOARD_F9 = 0x89,
    KEYBOARD_F10 = 0x8A,
    KEYBOARD_F11 = 0x8B,
    KEYBOARD_F12 = 0x8C,
    KEYBOARD_KEYPAD_7 = 0x47,
    KEYBOARD_KEYPAD_8 = 0x48,
    KEYBOARD_KEYPAD_9 = 0x49,
    KEYBOARD_KEYPAD_MINUS = 0x4A,
    KEYBOARD_KEYPAD_4 = 0x4B,
    KEYBOARD_KEYPAD_5 = 0x4C,
    KEYBOARD_KEYPAD_6 = 0x4D,
    KEYBOARD_KEYPAD_PLUS = 0x4E,
    KEYBOARD_KEYPAD_1 = 0x4F,
    KEYBOARD_KEYPAD_2 = 0x50,
    KEYBOARD_KEYPAD_3 = 0x51,
    KEYBOARD_KEYPAD_0 = 0x52,
    KEYBOARD_KEYPAD_PERIOD = 0x53,
    KEYBOARD_F13 = 0x92,
    KEYBOARD_F14 = 0x93,
    KEYBOARD_F15 = 0x94,
    KEYBOARD_F16 = 0x95,
    KEYBOARD_F17 = 0x96,
    KEYBOARD_F18 = 0x97,
    KEYBOARD_F19 = 0x98,
    KEYBOARD_F20 = 0x99,
    KEYBOARD_KEYPAD_ENTER = 0x9C,
    KEYBOARD_KEYPAD_EQUAL = 0x9D,
    KEYBOARD_F21 = 0x9E,
    KEYBOARD_F22 = 0x9F,

    // Special Keys (Pressed and Released States)
    KEYBOARD_KEYPAD_ENTER_PRESSED = 0xE01C,
    KEYBOARD_RIGHT_CTRL_PRESSED = 0xE01D,
    KEYBOARD_KEYPAD_SLASH_PRESSED = 0xE035,
    KEYBOARD_RIGHT_ALT_PRESSED = 0xE038,
    KEYBOARD_HOME_PRESSED = 0xE047,
    KEYBOARD_CURSOR_UP_PRESSED = 0xE048,
    KEYBOARD_PAGE_UP_PRESSED = 0xE049,
    KEYBOARD_CURSOR_LEFT_PRESSED = 0xE04B,
    KEYBOARD_CURSOR_RIGHT_PRESSED = 0xE04D,
    KEYBOARD_END_PRESSED = 0xE04F,
    KEYBOARD_CURSOR_DOWN_PRESSED = 0xE050,
    KEYBOARD_PAGE_DOWN_PRESSED = 0xE051,
    KEYBOARD_INSERT_PRESSED = 0xE052,
    KEYBOARD_DELETE_PRESSED = 0xE053,
    KEYBOARD_LEFT_GUI_PRESSED = 0xE05B,
    KEYBOARD_RIGHT_GUI_PRESSED = 0xE05C,
    KEYBOARD_APPS_PRESSED = 0xE05D,
    KEYBOARD_WAKE_PRESSED = 0xE063,

    // Released Keys
    KEYBOARD_PREVIOUS_TRACK_RELEASED = 0xE090,
    KEYBOARD_NEXT_TRACK_RELEASED = 0xE099,
    KEYBOARD_KEYPAD_ENTER_RELEASED = 0xE09C,
    KEYBOARD_RIGHT_CTRL_RELEASED = 0xE09D,
    KEYBOARD_KEYPAD_SLASH_RELEASED = 0xE0B5,
    KEYBOARD_RIGHT_ALT_RELEASED = 0xE0B8,
    KEYBOARD_HOME_RELEASED = 0xE0C7,
    KEYBOARD_CURSOR_UP_RELEASED = 0xE0C8,
    KEYBOARD_PAGE_UP_RELEASED = 0xE0C9,
    KEYBOARD_CURSOR_LEFT_RELEASED = 0xE0CB,
    KEYBOARD_CURSOR_RIGHT_RELEASED = 0xE0CD,
    KEYBOARD_END_RELEASED = 0xE0CF,
    KEYBOARD_CURSOR_DOWN_RELEASED = 0xE0D0,
    KEYBOARD_PAGE_DOWN_RELEASED = 0xE0D1,
    KEYBOARD_INSERT_RELEASED = 0xE0D2,
    KEYBOARD_DELETE_RELEASED = 0xE0D3,
    KEYBOARD_LEFT_GUI_RELEASED = 0xE0DB,
    KEYBOARD_RIGHT_GUI_RELEASED = 0xE0DC,
    KEYBOARD_APPS_RELEASED = 0xE0DD,
    KEYBOARD_WAKE_RELEASED = 0xE0E3,

    // Pause (multi-byte)
    KEYBOARD_PAUSE_PRESSED = 0xE1
} keyboard_non_printable_keys;
*/

#endif // ABOMINATION_H
